#!/bin/bash
APP_LOG=/home/centos/app-logs

DATE=$(date +%F:%H:%M:%S)

LOG_DIR=/home/centos/shellscript-logs

LOG_FILE=$LOG_DIR/$0-$DATE.log

FILES_TO_DELETE=$(find $APP_LOGS_DIR -name "*.log" -type f -mtime +14)

echo "script started executing at $DATE"

while read line
do
    echo "Deleting $line" &>> $LOGFILE
    rm -rf $line
done <<< $FILES_TO_DELETE